# Generated by Django 4.1.3 on 2022-12-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
    ]
