# Generated by Django 4.1.3 on 2022-12-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_pizza_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='url',
            field=models.URLField(default=0),
        ),
    ]
