# Generated by Django 3.2.16 on 2022-12-19 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_pizza_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='url',
        ),
    ]
